# Generated by Django 3.2.18 on 2023-03-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
    ]
