# Generated by Django 3.2.18 on 2023-03-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.recipe'),
        ),
    ]
