# Generated by Django 3.2.18 on 2023-03-12 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230312_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='liked_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
